// Generado por ia-poc/scripts/generar-catalogo.mjs; no editar a mano.
// Fuente: nota "Catálogo de entidades y titulares - Denuncias de corrupción" (directorios de gob.pe leídos el 2026-10-07) y
// ia-poc/datos/alias-entidades.json. Los nombres de los titulares rotan: solo se comparan como señal informativa, nunca deciden.
import { HuecoCatalogo, TipoEntidad } from "@/enums/filtro-corrupcion.enum.js";
import type { EntidadCatalogo } from "@/services/filtro-corrupcion/filtro-corrupcion.types.js";

export const CATALOGO_ENTIDADES: readonly EntidadCatalogo[] = [
  {
    codigo: "minsa",
    nombre: "Ministerio de Salud",
    tipo: TipoEntidad.MINISTERIO,
    alias: ["MINSA"],
    titular: { cargo: "Ministro de Salud", cargosEquivalentes: [], nombre: null },
    contactos: {
      OCI: [{ nombre: "Dante Aaron Yorges Avalos", cargo: "Jefe del Órgano de Control Institucional", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: [
        {
          nombre: "Mónica Tatiana Siverio Puycan",
          cargo: "Directora Ejecutiva de la Oficina de Transparencia y Anticorrupción (OTRANS)",
          correo: null,
        },
      ],
      PROCURADOR: [{ nombre: "José David Díaz López Aliaga", cargo: "Procurador Público del Ministerio de Salud", correo: null }],
    },
    huecos: [HuecoCatalogo.SIN_NOMBRE_TITULAR, HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD],
  },
  {
    codigo: "sis",
    nombre: "Seguro Integral de Salud",
    tipo: TipoEntidad.SIS,
    alias: ["SIS", "Sistema Integral de Salud", "Sistema Integrado de Salud"],
    titular: {
      cargo: "Jefa del Seguro Integral de Salud",
      cargosEquivalentes: ["Jefe del SIS", "Jefe Institucional"],
      nombre: "Zulma Anaya Chacón",
    },
    contactos: {
      OCI: [{ nombre: "Flavio Javier Aquize Díaz", cargo: "Jefe del OCI", correo: "faquize@sis.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: [{ nombre: "Julio Marlon Merodio Llanos", cargo: "Procurador Público", correo: "jmerodio@sis.gob.pe" }],
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD],
  },
  {
    codigo: "fissal",
    nombre: "Fondo Intangible Solidario de Salud",
    tipo: TipoEntidad.FONDO,
    alias: ["FISSAL"],
    titular: {
      cargo: "Jefe de la Unidad Ejecutora 002 - Fondo Intangible Solidario de Salud (FISSAL)",
      cargosEquivalentes: ["Jefe Institucional"],
      nombre: "Marco Antonio Salazar Rojas",
    },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "ins",
    nombre: "Instituto Nacional de Salud",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INS"],
    titular: {
      cargo: "Presidente Ejecutivo",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Jefe Institucional"],
      nombre: "Víctor Javier Suárez Moreno",
    },
    contactos: {
      OCI: [{ nombre: "Karin Sánchez Dávila", cargo: "Jefa del OCI", correo: "ksanchez@ins.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "susalud",
    nombre: "Superintendencia Nacional de Salud",
    tipo: TipoEntidad.ORGANISMO,
    alias: ["SUSALUD"],
    titular: { cargo: "Superintendente", cargosEquivalentes: ["Jefe Institucional"], nombre: "Martin Alonso Tantalean Del Aguila" },
    contactos: {
      OCI: [{ nombre: "Ximenna Marcela Chino Salas", cargo: "Jefa del OCI", correo: "xchino@susalud.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: [{ nombre: "Louis Ken Matsusaka Shimasaki", cargo: "Procurador Público", correo: "lmatsusaka@susalud.gob.pe" }],
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD],
  },
  {
    codigo: "inen",
    nombre: "Instituto Nacional de Enfermedades Neoplásicas",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INEN"],
    titular: {
      cargo: "Jefe Institucional",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Presidente Ejecutivo"],
      nombre: "Wilder Genaro Calmet Berrocal",
    },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "inmp",
    nombre: "Instituto Nacional Materno Perinatal",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INMP"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Felix Dasio Ayala Peralta",
    },
    contactos: {
      OCI: [{ nombre: "Carlos Ruben Moreno Leyva", cargo: "Jefe del OCI", correo: "cmoreno@iemp.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "insm",
    nombre: 'Instituto Nacional de Salud Mental "Honorio Delgado Hideyo- Noguchi"',
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INSM", "Instituto Nacional de Salud Mental"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Alfredo Federico Saavedra Castillo",
    },
    contactos: {
      OCI: [{ nombre: "Ronal Antonio Rivera Huaman", cargo: "Jefe del OCI", correo: "rrivera@insm.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "inr",
    nombre: "Instituto Nacional de Rehabilitación",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INR"],
    titular: {
      cargo: "DIRECTORA GENERAL",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Erika Giraldo Vizcarra",
    },
    contactos: {
      OCI: [{ nombre: "Julio César Balbín Mendoza", cargo: "Jefe del OCI", correo: "oci@inr.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "insnsb",
    nombre: "Instituto Nacional de Salud del Niño - San Borja",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INSNSB", "Instituto del Niño San Borja"],
    titular: {
      cargo: "Directora General (e)",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Melva Teodosia Benavides López",
    },
    contactos: {
      OCI: [{ nombre: "Julia Soledad Luján Calvo", cargo: "Jefa del OCI", correo: "jlujan@insnsb.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "incn",
    nombre: "Instituto Nacional Ciencias Neurológicas",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INCN", "Instituto Nacional de Ciencias Neurológicas"],
    titular: {
      cargo: "Director del Instituto Nacional de Ciencias Neurológicas",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Juan Manuel Sifuentes Monge",
    },
    contactos: {
      OCI: [{ nombre: "Yury Hugo Dávila Briceño", cargo: "Jefe del OCI", correo: "OCI-INCN@incn.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Yelimer Caucha Morales",
          cargo: "Secretario Técnico de los Órganos Instructores del Procedimiento Administrativo Disciplinario",
          correo: null,
        },
      ],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "insn",
    nombre: "Instituto Nacional de Salud del Niño - Breña",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INSN", "Instituto del Niño Breña"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Eladio Benjamín Pimentel Román",
    },
    contactos: {
      OCI: [{ nombre: "Paola Rossana Gonzales Albornoz", cargo: "Jefa del OCI", correo: "pgonzalesa@insn.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "ino",
    nombre: "Instituto Nacional de Oftalmología",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INO"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Félix Antonio Torres Cotrina",
    },
    contactos: {
      OCI: [{ nombre: "Ericka Andrea Gómez Hidalgo", cargo: "Jefa del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: [
        { nombre: "Melissa Lorena Beltrán Moreno", cargo: "Secretaria Técnica de la Secretaría de los Órganos Instructores", correo: null },
      ],
      INTEGRIDAD: [
        {
          nombre: "Daniel Marcelo Gutiérrez Herrera",
          cargo: "Coordinador de la Unidad Funcional de Integridad",
          correo: "dgutierrez@ino.gob.pe",
        },
      ],
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hnhu",
    nombre: "Hospital Nacional Hipólito Unanue",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNHU", "Hospital Hipólito Unanue"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Moisés Enrique Tambini Acosta",
    },
    contactos: {
      OCI: [{ nombre: "Daniel Adolfo Olivas Ocaña", cargo: "Jefe del OCI", correo: "control.institucional@hnhu.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hhv",
    nombre: "Hospital Hermilio Valdizan",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HHV"],
    titular: {
      cargo: "DIRECTOR(a) GENERAL",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Gloria Cueva Vergara",
    },
    contactos: {
      OCI: [{ nombre: "Max Arturo Gómez Casaico", cargo: "Jefe del OCI", correo: "mgomez@hhv.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hnal",
    nombre: "Hospital Nacional Arzobispo Loayza",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNAL", "Hospital Loayza", "Hospital Loaiza", "Hospital Nacional Arzobispo Loayza"],
    titular: {
      cargo: "Director General del Hospital Nacional Arzobispo Loayza",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Eduardo Franklin Yong Motta",
    },
    contactos: {
      OCI: [{ nombre: "Manuel Godofredo Arancel Díaz", cargo: "Jefe del OCI", correo: "marancel@hospitalloayza.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Elizabeth Lucila Vargas Fabes",
          cargo: "Secretaria Técnica de los Órganos Instructores",
          correo: "evargasf@hospitalloayza.gob.pe",
        },
        { nombre: "Rosario Cerrón Torres", cargo: "Jefa de la Unidad de Secretaría Técnica", correo: "rcerron@hospitalloayza.gob.pe" },
      ],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR, HuecoCatalogo.DIRECTORIO_INCOMPLETO],
  },
  {
    codigo: "hvlh",
    nombre: "Hospital Víctor Larco Herrera",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HVLH", "Hospital Larco Herrera"],
    titular: {
      cargo: "Directora General",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Judy Soraya López Arias",
    },
    contactos: {
      OCI: [{ nombre: "Mery Angie Odicio Rivera", cargo: "Jefa del OCI", correo: "modicio@hvlh.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hnseb",
    nombre: "Hospital Nacional Sergio Bernales",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNSEB", "Hospital Sergio Bernales"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Oscar Uchuya Maurtua",
    },
    contactos: {
      OCI: [{ nombre: "Jade Ruth Chávez Rosales", cargo: "Jefa del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hndm",
    nombre: "Hospital Nacional Dos de Mayo",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNDM", "Hospital Dos de Mayo", "Hospital Nacional Dos de Mayo"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Víctor Rafael Gonzáles Pérez",
    },
    contactos: {
      OCI: [{ nombre: "Omar Enrique Nalvarte Estrada", cargo: "Jefe del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hsr",
    nombre: "Hospital Santa Rosa",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HSR"],
    titular: {
      cargo: "DIRECTOR GENERAL",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Luis Marcelo Guzmán Aquije",
    },
    contactos: {
      OCI: [{ nombre: "Julio César Balbín Mendoza", cargo: "Jefe del OCI", correo: "jbalbin@hsr.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hh",
    nombre: "Hospital de Huaycán",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["Hospital Huaycán"],
    titular: {
      cargo: "Director del Hospital de Huaycan",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Maycol Luis Baldeón Cruzado",
    },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "hnch",
    nombre: "Hospital Cayetano Heredia",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNCH", "Hospital Nacional Cayetano Heredia"],
    titular: {
      cargo: "Director General del Hospital Nacional Cayetano Heredia",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Manuel Alberto Díaz De Los Santos",
    },
    contactos: {
      OCI: [{ nombre: "Nela Aliaga Ponce", cargo: "Jefa del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hejcu",
    nombre: "Hospital de Emergencias José Casimiro Ulloa",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HEJCU", "Hospital Casimiro Ulloa", "Hospital de Emergencias Casimiro Ulloa"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Raúl Hinostroza Castillo",
    },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "hma",
    nombre: "Hospital María Auxiliadora",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HMA"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Edgar Benito Pacheco",
    },
    contactos: {
      OCI: [{ nombre: "Mariela Nicolasa Medina Chaupi", cargo: "Jefa del OCI", correo: "mmedinac@contraloria.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hep",
    nombre: "Hospital de Emergencias Pediátricas",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HEP"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Jorge Jáuregui Miranda",
    },
    contactos: {
      OCI: null,
      SECRETARIA_TECNICA_PAD: [{ nombre: "Luz Ofelia Martínez Velezmoro", cargo: "Secretaria Técnica", correo: null }],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_OCI, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hsjl",
    nombre: "Hospital San Juan de Lurigancho",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HSJL", "Hospital de San Juan de Lurigancho"],
    titular: {
      cargo: "Directora Ejecutiva",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Ofelia Rosaura Aguirre Romero",
    },
    contactos: {
      OCI: [{ nombre: "Carlos Uldarico Bonett Portugal", cargo: "Jefe del OCI", correo: "carlos.bonettp@hospitalsjl.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [
      HuecoCatalogo.TITULAR_POR_CONFIRMAR,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
    ],
  },
  {
    codigo: "heves",
    nombre: "Hospital de Emergencias Villa El Salvador",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HEVES", "Hospital de Villa El Salvador"],
    titular: {
      cargo: "Director Ejecutivo",
      cargosEquivalentes: ["Director General", "Director del Hospital"],
      nombre: "Hugo Efrend Rojas Olivera",
    },
    contactos: {
      OCI: [{ nombre: "Liana Valeria Díaz Chaña", cargo: "Jefa del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: [
        { nombre: "Clever Pabel Acaro Zeta", cargo: "Secretario Técnico de los Órganos Instructores", correo: "clever.acaro@heves.gob.pe" },
      ],
      INTEGRIDAD: [{ nombre: "René Camilla Teniente", cargo: "Oficial de Integridad", correo: "rene.camilla@heves.gob.pe" }],
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hcllh",
    nombre: "Hospital Carlos Lanfranco La Hoz",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HCLLH", "Hospital Lanfranco La Hoz"],
    titular: {
      cargo: "Director Ejecutivo",
      cargosEquivalentes: ["Director General", "Director del Hospital"],
      nombre: "Luis Enrique Ríos Olivos",
    },
    contactos: {
      OCI: [{ nombre: "Marco Antonio Guevara Soto", cargo: "Jefe del OCI", correo: "oci@hcllh.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hjatch",
    nombre: "Hospital José Agurto Tello de Chosica",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HJATCH", "Hospital de Chosica", "Hospital José Agurto Tello"],
    titular: {
      cargo: "Director Ejecutivo",
      cargosEquivalentes: ["Director General", "Director del Hospital"],
      nombre: "Juan Pablo Sachun Alanya",
    },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "honadomani-sb",
    nombre: "Hospital Nacional Docente Madre Niño San Bartolomé",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HONADOMANI SB", "HONADOMANI", "Hospital San Bartolomé"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Aldo César Benel Chamaya",
    },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "hlev",
    nombre: "Hospital de Lima Este Vitarte",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HLEV", "Hospital Vitarte"],
    titular: {
      cargo: "Director",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Hugo Wiliam Peña Lovaton",
    },
    contactos: {
      OCI: [{ nombre: "Graciela Quito Rivera", cargo: "Jefa del OCI", correo: "gquito@hlev.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Ramón Farro Samamé",
          cargo: "Secretario Técnico del Procedimiento Administrativo Disciplinario",
          correo: "rfarro@hlev.gob.pe",
        },
      ],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "cenares",
    nombre: "Centro Nacional de Abastecimiento de Recursos Estratégicos en Salud",
    tipo: TipoEntidad.CENTRO,
    alias: ["CENARES"],
    titular: {
      cargo: "Directora General",
      cargosEquivalentes: ["Director General", "Director Ejecutivo"],
      nombre: "Patricia Isabel Suárez Beyodas",
    },
    contactos: {
      OCI: [{ nombre: "Livia Militza Calizaya De La Sota", cargo: "Jefa del OCI", correo: "lcalizaya@contraloria.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "José Antonio Vargas Molina",
          cargo: "Secretario Técnico Suplente de los Órganos Instructores",
          correo: "jvargas@cenares.gob.pe",
        },
      ],
      INTEGRIDAD: [
        { nombre: "Romelia Clorinda Paredes Tuesta", cargo: "Oficial (e) de Integridad Institucional", correo: "rparedes@cenares.gob.pe" },
      ],
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "pronis",
    nombre: "Programa Nacional de Inversiones en Salud",
    tipo: TipoEntidad.PROGRAMA,
    alias: ["PRONIS"],
    titular: { cargo: "Coordinador General", cargosEquivalentes: ["Director Ejecutivo"], nombre: "David Guillermo Miranda Herrera" },
    contactos: {
      OCI: [{ nombre: "Jesús Enrique Echavarria Pomalaza", cargo: "Jefe del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "diris-le",
    nombre: "Dirección General de Redes Integradas de Salud Lima Este",
    tipo: TipoEntidad.DIRIS,
    alias: ["DIRIS Lima Este", "Dirección de Redes Integradas de Salud Lima Este"],
    titular: { cargo: "DIRECTOR GENERAL", cargosEquivalentes: ["Director de la DIRIS"], nombre: "Norberto Yamunaqué Asanza" },
    contactos: {
      OCI: [{ nombre: "Katia Fabiola Ortiz Yañez", cargo: "Jefa del OCI", correo: "kortiz@dirislimaeste.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "diris-ln",
    nombre: "Dirección General de Redes Integradas de Salud Lima Norte",
    tipo: TipoEntidad.DIRIS,
    alias: ["DIRIS LN", "DIRIS Lima Norte", "Dirección de Redes Integradas de Salud Lima Norte"],
    titular: {
      cargo: "DIRECTORA GENERAL",
      cargosEquivalentes: ["Director General", "Director de la DIRIS"],
      nombre: "Libny Betsabeth More Huamán",
    },
    contactos: {
      OCI: [{ nombre: "Elizabeth Ruth Ríos Chuquinaupa", cargo: "Jefa del OCI", correo: "elizabeth.rios@dirisln.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Luis Alberto David Orcotoma Machuca",
          cargo: "Secretario Técnico del Procedimiento Administrativo Disciplinario",
          correo: "luis.orcotoma@dirisln.gob.pe",
        },
      ],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "diris-lc",
    nombre: "Dirección General de Redes Integradas de Salud Lima Centro",
    tipo: TipoEntidad.DIRIS,
    alias: ["DIRIS LC", "DIRIS Lima Centro", "Dirección de Redes Integradas de Salud Lima Centro"],
    titular: { cargo: "Director General", cargosEquivalentes: ["Director de la DIRIS"], nombre: "Julio Miguel Flores Retuerto" },
    contactos: {
      OCI: [{ nombre: "Lisbeth Carolina Lopez Peña", cargo: "Jefa del OCI", correo: "oci@dirislimacentro.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "diris-ls",
    nombre: "Dirección General de Redes Integradas de Salud Lima Sur",
    tipo: TipoEntidad.DIRIS,
    alias: ["DIRIS LS", "DIRIS Lima Sur", "Dirección de Redes Integradas de Salud Lima Sur"],
    titular: { cargo: "Director General", cargosEquivalentes: ["Director de la DIRIS"], nombre: "Mario Eduardo Izquierdo Hernández" },
    contactos: {
      OCI: [{ nombre: "Merici De Los Ángeles Huertas Navarro", cargo: "Jefa del OCI", correo: "mhuertas@dirislimasur.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Carlos Felix Vega Venegas",
          cargo: "Secretario Técnico de los Órganos Instructores",
          correo: "cvega@dirislimasur.gob.pe",
        },
      ],
      INTEGRIDAD: [
        {
          nombre: "Jair Alexander Patiño la Rosa",
          cargo: "Jefe de la Oficina de Integridad Institucional",
          correo: "jpatino@dirislimasur.gob.pe",
        },
      ],
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_PROCURADOR],
  },
];
