// Generado por ia-poc/scripts/generar-catalogo.mjs; no editar a mano.
// Fuente: nota "Catálogo de entidades y titulares - Denuncias de corrupción" (destino de la denuncia contra el titular y
// directorios de gob.pe leídos el 2026-10-07) y ia-poc/datos/alias-entidades.json.
// `alias`: sigla y nombres cortos escritos a mano. `aliasDerivados`: variantes generadas del nombre oficial y la sigla (sin
// "Hospital"/"Nacional"/"de", con artículo, con faltas de ortografía frecuentes); los ambiguos están en ia-poc/datos/alias-ambiguos.json.
// Los nombres de los titulares rotan: solo se comparan como señal informativa, nunca deciden.
import { HuecoCatalogo, TipoEntidad } from "@/enums/filtro-corrupcion.enum.js";
import type { EntidadCatalogo } from "@/services/filtro-corrupcion/filtro-corrupcion.types.js";

export const CATALOGO_ENTIDADES: readonly EntidadCatalogo[] = [
  {
    codigo: "minsa",
    nombre: "Ministerio de Salud",
    tipo: TipoEntidad.MINISTERIO,
    alias: ["MINSA"],
    aliasDerivados: [],
    titular: { cargo: "Ministro de Salud", cargosEquivalentes: [], nombre: null },
    destinoSiTitular: {
      texto: "Servidores y funcionarios de todos los órganos de la administración central (excepción del Ministro)",
      entidadDestinoCodigo: null,
    },
    contactos: {
      OCI: [{ nombre: "Dante Aaron Yorges Avalos", cargo: "Jefe del Órgano de Control Institucional", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: [
        {
          nombre: "Mónica Tatiana Siverio Puycan",
          cargo: "Directora Ejecutiva de la Oficina de Transparencia y Anticorrupción (OTRANS)",
          correo: null,
        },
      ],
      PROCURADOR: [{ nombre: "José David Díaz López Aliaga", cargo: "Procurador Público del Ministerio de Salud", correo: null }],
    },
    huecos: [HuecoCatalogo.SIN_NOMBRE_TITULAR, HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD],
  },
  {
    codigo: "sis",
    nombre: "Seguro Integral de Salud",
    tipo: TipoEntidad.SIS,
    alias: ["SIS", "Sistema Integral de Salud", "Sistema Integrado de Salud"],
    aliasDerivados: [],
    titular: {
      cargo: "Jefa del Seguro Integral de Salud",
      cargosEquivalentes: ["Jefe del SIS", "Jefe Institucional"],
      nombre: "Zulma Anaya Chacón",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Flavio Javier Aquize Díaz", cargo: "Jefe del OCI", correo: "faquize@sis.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: [{ nombre: "Julio Marlon Merodio Llanos", cargo: "Procurador Público", correo: "jmerodio@sis.gob.pe" }],
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD],
  },
  {
    codigo: "fissal",
    nombre: "Fondo Intangible Solidario de Salud",
    tipo: TipoEntidad.FONDO,
    alias: ["FISSAL"],
    aliasDerivados: ["fisal"],
    titular: {
      cargo: "Jefe de la Unidad Ejecutora 002 - Fondo Intangible Solidario de Salud (FISSAL)",
      cargosEquivalentes: ["Jefe Institucional"],
      nombre: "Marco Antonio Salazar Rojas",
    },
    destinoSiTitular: { texto: "SIS (Sistema Integrado de Salud, según la nota (2*) de la lista)", entidadDestinoCodigo: "sis" },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "ins",
    nombre: "Instituto Nacional de Salud",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INS"],
    aliasDerivados: [],
    titular: {
      cargo: "Presidente Ejecutivo",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Jefe Institucional"],
      nombre: "Víctor Javier Suárez Moreno",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Karin Sánchez Dávila", cargo: "Jefa del OCI", correo: "ksanchez@ins.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "susalud",
    nombre: "Superintendencia Nacional de Salud",
    tipo: TipoEntidad.ORGANISMO,
    alias: ["SUSALUD"],
    aliasDerivados: [],
    titular: { cargo: "Superintendente", cargosEquivalentes: ["Jefe Institucional"], nombre: "Martin Alonso Tantalean Del Aguila" },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Ximenna Marcela Chino Salas", cargo: "Jefa del OCI", correo: "xchino@susalud.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: [{ nombre: "Louis Ken Matsusaka Shimasaki", cargo: "Procurador Público", correo: "lmatsusaka@susalud.gob.pe" }],
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD],
  },
  {
    codigo: "inen",
    nombre: "Instituto Nacional de Enfermedades Neoplásicas",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INEN", "las Neoplásicas"],
    aliasDerivados: [
      "enfermedades neoplacicas",
      "enfermedades neoplasicas",
      "enfermedades neoplazicas",
      "instituto de enfermedades neoplacicas",
      "instituto de enfermedades neoplasicas",
      "instituto de enfermedades neoplazicas",
      "instituto de neoplacicas",
      "instituto de neoplasicas",
      "instituto de neoplazicas",
      "instituto enfermedades neoplacicas",
      "instituto enfermedades neoplasicas",
      "instituto enfermedades neoplazicas",
      "instituto nacional enfermedades neoplacicas",
      "instituto nacional enfermedades neoplasicas",
      "instituto nacional enfermedades neoplazicas",
      "instituto nacional neoplacicas",
      "instituto nacional neoplasicas",
      "instituto nacional neoplazicas",
      "instituto neoplacicas",
      "instituto neoplasicas",
      "instituto neoplazicas",
      "neoplacicas",
      "neoplasicas",
      "neoplazicas",
    ],
    titular: {
      cargo: "Jefe Institucional",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Presidente Ejecutivo"],
      nombre: "Wilder Genaro Calmet Berrocal",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "inmp",
    nombre: "Instituto Nacional Materno Perinatal",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INMP"],
    aliasDerivados: ["instituto de materno perinatal", "instituto materno perinatal"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Felix Dasio Ayala Peralta",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Carlos Ruben Moreno Leyva", cargo: "Jefe del OCI", correo: "cmoreno@iemp.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "insm",
    nombre: 'Instituto Nacional de Salud Mental "Honorio Delgado Hideyo- Noguchi"',
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INSM", "Instituto Nacional de Salud Mental", "Honorio Delgado", "Noguchi"],
    aliasDerivados: [],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Alfredo Federico Saavedra Castillo",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Ronal Antonio Rivera Huaman", cargo: "Jefe del OCI", correo: "rrivera@insm.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "inr",
    nombre: "Instituto Nacional de Rehabilitación",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INR"],
    aliasDerivados: ["instituto de rehabilitacion", "instituto nacional rehabilitacion", "instituto rehabilitacion"],
    titular: {
      cargo: "DIRECTORA GENERAL",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Erika Giraldo Vizcarra",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Julio César Balbín Mendoza", cargo: "Jefe del OCI", correo: "oci@inr.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "insnsb",
    nombre: "Instituto Nacional de Salud del Niño - San Borja",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INSNSB", "Instituto del Niño San Borja"],
    aliasDerivados: [],
    titular: {
      cargo: "Directora General (e)",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Melva Teodosia Benavides López",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Julia Soledad Luján Calvo", cargo: "Jefa del OCI", correo: "jlujan@insnsb.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "incn",
    nombre: "Instituto Nacional Ciencias Neurológicas",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INCN", "Instituto Nacional de Ciencias Neurológicas"],
    aliasDerivados: ["instituto ciencias neurologicas", "instituto de ciencias neurologicas"],
    titular: {
      cargo: "Director del Instituto Nacional de Ciencias Neurológicas",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Juan Manuel Sifuentes Monge",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Yury Hugo Dávila Briceño", cargo: "Jefe del OCI", correo: "OCI-INCN@incn.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Yelimer Caucha Morales",
          cargo: "Secretario Técnico de los Órganos Instructores del Procedimiento Administrativo Disciplinario",
          correo: null,
        },
      ],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "insn",
    nombre: "Instituto Nacional de Salud del Niño - Breña",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INSN", "Instituto del Niño Breña"],
    aliasDerivados: [],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Eladio Benjamín Pimentel Román",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Paola Rossana Gonzales Albornoz", cargo: "Jefa del OCI", correo: "pgonzalesa@insn.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "ino",
    nombre: "Instituto Nacional de Oftalmología",
    tipo: TipoEntidad.INSTITUTO,
    alias: ["INO"],
    aliasDerivados: ["instituto de oftalmologia", "instituto nacional oftalmologia", "instituto oftalmologia"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Jefe Institucional", "Presidente Ejecutivo"],
      nombre: "Félix Antonio Torres Cotrina",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Ericka Andrea Gómez Hidalgo", cargo: "Jefa del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: [
        { nombre: "Melissa Lorena Beltrán Moreno", cargo: "Secretaria Técnica de la Secretaría de los Órganos Instructores", correo: null },
      ],
      INTEGRIDAD: [
        {
          nombre: "Daniel Marcelo Gutiérrez Herrera",
          cargo: "Coordinador de la Unidad Funcional de Integridad",
          correo: "dgutierrez@ino.gob.pe",
        },
      ],
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hnhu",
    nombre: "Hospital Nacional Hipólito Unanue",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNHU", "Hospital Hipólito Unanue"],
    aliasDerivados: [
      "hipolito unanue",
      "hospital de hipolito unanue",
      "hospital de ipolito unanue",
      "hospital de unanue",
      "hospital ipolito unanue",
      "hospital nacional ipolito unanue",
      "hospital nacional unanue",
      "hospital unanue",
      "ipolito unanue",
      "unanue",
    ],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Moisés Enrique Tambini Acosta",
    },
    destinoSiTitular: { texto: "DIRIS LIMA ESTE (Dirección de Redes Integradas de Salud Lima Este)", entidadDestinoCodigo: "diris-le" },
    contactos: {
      OCI: [{ nombre: "Daniel Adolfo Olivas Ocaña", cargo: "Jefe del OCI", correo: "control.institucional@hnhu.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hhv",
    nombre: "Hospital Hermilio Valdizan",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HHV"],
    aliasDerivados: [
      "baldizan",
      "ermilio valdizan",
      "hermilio baldizan",
      "hermilio valdisan",
      "hermilio valdizan",
      "hospital baldizan",
      "hospital de baldizan",
      "hospital de ermilio valdizan",
      "hospital de hermilio baldizan",
      "hospital de hermilio valdisan",
      "hospital de hermilio valdizan",
      "hospital de valdisan",
      "hospital de valdizan",
      "hospital ermilio valdizan",
      "hospital hermilio baldizan",
      "hospital hermilio valdisan",
      "hospital valdisan",
      "hospital valdizan",
      "valdisan",
      "valdizan",
    ],
    titular: {
      cargo: "DIRECTOR(a) GENERAL",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Gloria Cueva Vergara",
    },
    destinoSiTitular: { texto: "DIRIS LIMA ESTE (Dirección de Redes Integradas de Salud Lima Este)", entidadDestinoCodigo: "diris-le" },
    contactos: {
      OCI: [{ nombre: "Max Arturo Gómez Casaico", cargo: "Jefe del OCI", correo: "mgomez@hhv.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hnal",
    nombre: "Hospital Nacional Arzobispo Loayza",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNAL", "Hospital Loayza", "Hospital Loaiza", "Hospital Nacional Arzobispo Loayza", "el Loayza", "el Loaiza"],
    aliasDerivados: [
      "arsobispo loayza",
      "arzobispo loaiza",
      "arzobispo loaysa",
      "arzobispo loayza",
      "arzobizpo loayza",
      "arzovispo loayza",
      "hospital arsobispo loayza",
      "hospital arzobispo loaiza",
      "hospital arzobispo loaysa",
      "hospital arzobispo loayza",
      "hospital arzobizpo loayza",
      "hospital arzovispo loayza",
      "hospital de arsobispo loayza",
      "hospital de arzobispo loaiza",
      "hospital de arzobispo loaysa",
      "hospital de arzobispo loayza",
      "hospital de arzobizpo loayza",
      "hospital de arzovispo loayza",
      "hospital de loaiza",
      "hospital de loaysa",
      "hospital de loayza",
      "hospital loaysa",
      "hospital nacional arsobispo loayza",
      "hospital nacional arzobispo loaiza",
      "hospital nacional arzobispo loaysa",
      "hospital nacional arzobizpo loayza",
      "hospital nacional arzovispo loayza",
      "hospital nacional loaiza",
      "hospital nacional loaysa",
      "hospital nacional loayza",
      "loaiza",
      "loaysa",
      "loayza",
    ],
    titular: {
      cargo: "Director General del Hospital Nacional Arzobispo Loayza",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Eduardo Franklin Yong Motta",
    },
    destinoSiTitular: { texto: "DIRIS LIMA CENTRO (Dirección de Redes Integradas de Salud Lima Centro)", entidadDestinoCodigo: "diris-lc" },
    contactos: {
      OCI: [{ nombre: "Manuel Godofredo Arancel Díaz", cargo: "Jefe del OCI", correo: "marancel@hospitalloayza.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Elizabeth Lucila Vargas Fabes",
          cargo: "Secretaria Técnica de los Órganos Instructores",
          correo: "evargasf@hospitalloayza.gob.pe",
        },
        { nombre: "Rosario Cerrón Torres", cargo: "Jefa de la Unidad de Secretaría Técnica", correo: "rcerron@hospitalloayza.gob.pe" },
      ],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR, HuecoCatalogo.DIRECTORIO_INCOMPLETO],
  },
  {
    codigo: "hvlh",
    nombre: "Hospital Víctor Larco Herrera",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HVLH", "Hospital Larco Herrera"],
    aliasDerivados: [
      "al errera",
      "al herrera",
      "del errera",
      "del herrera",
      "el errera",
      "el herrera",
      "hospital de errera",
      "hospital de herrera",
      "hospital de larco errera",
      "hospital de larco herrera",
      "hospital de victor larco errera",
      "hospital de victor larco herrera",
      "hospital errera",
      "hospital herrera",
      "hospital larco errera",
      "hospital victor larco errera",
      "la errera",
      "la herrera",
      "larco errera",
      "larco herrera",
      "victor larco errera",
      "victor larco herrera",
    ],
    titular: {
      cargo: "Directora General",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Judy Soraya López Arias",
    },
    destinoSiTitular: { texto: "DIRIS LIMA CENTRO (Dirección de Redes Integradas de Salud Lima Centro)", entidadDestinoCodigo: "diris-lc" },
    contactos: {
      OCI: [{ nombre: "Mery Angie Odicio Rivera", cargo: "Jefa del OCI", correo: "modicio@hvlh.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hnseb",
    nombre: "Hospital Nacional Sergio Bernales",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNSEB", "Hospital Sergio Bernales", "el Sergio Bernales"],
    aliasDerivados: [
      "bernales",
      "cergio bernales",
      "hospital bernales",
      "hospital cergio bernales",
      "hospital de bernales",
      "hospital de cergio bernales",
      "hospital de sergio bernales",
      "hospital de sergio vernales",
      "hospital de vernales",
      "hospital de zergio bernales",
      "hospital nacional bernales",
      "hospital nacional cergio bernales",
      "hospital nacional sergio vernales",
      "hospital nacional vernales",
      "hospital nacional zergio bernales",
      "hospital sergio vernales",
      "hospital vernales",
      "hospital zergio bernales",
      "sergio bernales",
      "sergio vernales",
      "vernales",
      "zergio bernales",
    ],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Oscar Uchuya Maurtua",
    },
    destinoSiTitular: { texto: "DIRIS LIMA NORTE (Dirección de Redes Integradas de Salud Lima Norte)", entidadDestinoCodigo: "diris-ln" },
    contactos: {
      OCI: [{ nombre: "Jade Ruth Chávez Rosales", cargo: "Jefa del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hndm",
    nombre: "Hospital Nacional Dos de Mayo",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNDM", "Hospital Dos de Mayo", "Hospital Nacional Dos de Mayo", "el Dos de Mayo"],
    aliasDerivados: ["al dos de mayo", "del dos de mayo", "hospital de dos de mayo", "la dos de mayo"],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Víctor Rafael Gonzáles Pérez",
    },
    destinoSiTitular: { texto: "DIRIS LIMA CENTRO (Dirección de Redes Integradas de Salud Lima Centro)", entidadDestinoCodigo: "diris-lc" },
    contactos: {
      OCI: [{ nombre: "Omar Enrique Nalvarte Estrada", cargo: "Jefe del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hsr",
    nombre: "Hospital Santa Rosa",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HSR"],
    aliasDerivados: ["al santa rosa", "del santa rosa", "el santa rosa", "hospital de santa rosa", "la santa rosa"],
    titular: {
      cargo: "DIRECTOR GENERAL",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Luis Marcelo Guzmán Aquije",
    },
    destinoSiTitular: { texto: "DIRIS LIMA CENTRO (Dirección de Redes Integradas de Salud Lima Centro)", entidadDestinoCodigo: "diris-lc" },
    contactos: {
      OCI: [{ nombre: "Julio César Balbín Mendoza", cargo: "Jefe del OCI", correo: "jbalbin@hsr.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hh",
    nombre: "Hospital de Huaycán",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["Hospital Huaycán"],
    aliasDerivados: ["hospital de huaican", "hospital de uaycan", "hospital huaican", "hospital uaycan"],
    titular: {
      cargo: "Director del Hospital de Huaycan",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Maycol Luis Baldeón Cruzado",
    },
    destinoSiTitular: { texto: "DIRIS LIMA ESTE (Dirección de Redes Integradas de Salud Lima Este)", entidadDestinoCodigo: "diris-le" },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "hnch",
    nombre: "Hospital Cayetano Heredia",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HNCH", "Hospital Nacional Cayetano Heredia", "el Cayetano"],
    aliasDerivados: [
      "al eredia",
      "al heredia",
      "caietano heredia",
      "calletano heredia",
      "cayetano eredia",
      "cayetano heredia",
      "del eredia",
      "del heredia",
      "el eredia",
      "el heredia",
      "hospital caietano heredia",
      "hospital calletano heredia",
      "hospital cayetano eredia",
      "hospital de caietano heredia",
      "hospital de calletano heredia",
      "hospital de cayetano eredia",
      "hospital de cayetano heredia",
      "hospital de eredia",
      "hospital de heredia",
      "hospital eredia",
      "hospital heredia",
      "la eredia",
      "la heredia",
    ],
    titular: {
      cargo: "Director General del Hospital Nacional Cayetano Heredia",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Manuel Alberto Díaz De Los Santos",
    },
    destinoSiTitular: { texto: "DIRIS LIMA NORTE (Dirección de Redes Integradas de Salud Lima Norte)", entidadDestinoCodigo: "diris-ln" },
    contactos: {
      OCI: [{ nombre: "Nela Aliaga Ponce", cargo: "Jefa del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hejcu",
    nombre: "Hospital de Emergencias José Casimiro Ulloa",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HEJCU", "Hospital Casimiro Ulloa", "Hospital de Emergencias Casimiro Ulloa", "el Ulloa"],
    aliasDerivados: [
      "cacimiro ulloa",
      "casimiro ulloa",
      "casimiro uyoa",
      "cazimiro ulloa",
      "hospital cacimiro ulloa",
      "hospital casimiro uyoa",
      "hospital cazimiro ulloa",
      "hospital de cacimiro ulloa",
      "hospital de casimiro ulloa",
      "hospital de casimiro uyoa",
      "hospital de cazimiro ulloa",
      "hospital de jose cacimiro ulloa",
      "hospital de jose casimiro ulloa",
      "hospital de jose casimiro uyoa",
      "hospital de jose cazimiro ulloa",
      "hospital de ulloa",
      "hospital de uyoa",
      "hospital jose cacimiro ulloa",
      "hospital jose casimiro ulloa",
      "hospital jose casimiro uyoa",
      "hospital jose cazimiro ulloa",
      "hospital ulloa",
      "hospital uyoa",
      "jose cacimiro ulloa",
      "jose casimiro ulloa",
      "jose casimiro uyoa",
      "jose cazimiro ulloa",
      "ulloa",
      "uyoa",
    ],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Raúl Hinostroza Castillo",
    },
    destinoSiTitular: { texto: "DIRIS LIMA CENTRO (Dirección de Redes Integradas de Salud Lima Centro)", entidadDestinoCodigo: "diris-lc" },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "hma",
    nombre: "Hospital María Auxiliadora",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HMA"],
    aliasDerivados: [
      "auxiliadora",
      "hospital auxiliadora",
      "hospital de auxiliadora",
      "hospital de maria auxiliadora",
      "maria auxiliadora",
    ],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Edgar Benito Pacheco",
    },
    destinoSiTitular: { texto: "DIRIS LIMA SUR (Dirección de Redes Integradas de Salud Lima Sur)", entidadDestinoCodigo: "diris-ls" },
    contactos: {
      OCI: [{ nombre: "Mariela Nicolasa Medina Chaupi", cargo: "Jefa del OCI", correo: "mmedinac@contraloria.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hep",
    nombre: "Hospital de Emergencias Pediátricas",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HEP"],
    aliasDerivados: [],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Jorge Jáuregui Miranda",
    },
    destinoSiTitular: { texto: "DIRIS LIMA CENTRO (Dirección de Redes Integradas de Salud Lima Centro)", entidadDestinoCodigo: "diris-lc" },
    contactos: {
      OCI: null,
      SECRETARIA_TECNICA_PAD: [{ nombre: "Luz Ofelia Martínez Velezmoro", cargo: "Secretaria Técnica", correo: null }],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_OCI, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hsjl",
    nombre: "Hospital San Juan de Lurigancho",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HSJL", "Hospital de San Juan de Lurigancho", "Hospital SJL"],
    aliasDerivados: [],
    titular: {
      cargo: "Directora Ejecutiva",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Ofelia Rosaura Aguirre Romero",
    },
    destinoSiTitular: { texto: "DIRIS LIMA CENTRO (Dirección de Redes Integradas de Salud Lima Centro)", entidadDestinoCodigo: "diris-lc" },
    contactos: {
      OCI: [{ nombre: "Carlos Uldarico Bonett Portugal", cargo: "Jefe del OCI", correo: "carlos.bonettp@hospitalsjl.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [
      HuecoCatalogo.TITULAR_POR_CONFIRMAR,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
    ],
  },
  {
    codigo: "heves",
    nombre: "Hospital de Emergencias Villa El Salvador",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HEVES", "Hospital de Villa El Salvador"],
    aliasDerivados: ["hospital villa el salvador"],
    titular: {
      cargo: "Director Ejecutivo",
      cargosEquivalentes: ["Director General", "Director del Hospital"],
      nombre: "Hugo Efrend Rojas Olivera",
    },
    destinoSiTitular: { texto: "DIRIS LIMA SUR (Dirección de Redes Integradas de Salud Lima Sur)", entidadDestinoCodigo: "diris-ls" },
    contactos: {
      OCI: [{ nombre: "Liana Valeria Díaz Chaña", cargo: "Jefa del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: [
        { nombre: "Clever Pabel Acaro Zeta", cargo: "Secretario Técnico de los Órganos Instructores", correo: "clever.acaro@heves.gob.pe" },
      ],
      INTEGRIDAD: [{ nombre: "René Camilla Teniente", cargo: "Oficial de Integridad", correo: "rene.camilla@heves.gob.pe" }],
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hcllh",
    nombre: "Hospital Carlos Lanfranco La Hoz",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HCLLH", "Hospital Lanfranco La Hoz", "Lanfranco La Hoz", "Lanfranco"],
    aliasDerivados: ["carlos lanfranco la hoz", "hclh", "hospital de carlos lanfranco la hoz"],
    titular: {
      cargo: "Director Ejecutivo",
      cargosEquivalentes: ["Director General", "Director del Hospital"],
      nombre: "Luis Enrique Ríos Olivos",
    },
    destinoSiTitular: { texto: "DIRIS LIMA NORTE (Dirección de Redes Integradas de Salud Lima Norte)", entidadDestinoCodigo: "diris-ln" },
    contactos: {
      OCI: [{ nombre: "Marco Antonio Guevara Soto", cargo: "Jefe del OCI", correo: "oci@hcllh.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "hjatch",
    nombre: "Hospital José Agurto Tello de Chosica",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HJATCH", "Hospital de Chosica", "Hospital José Agurto Tello"],
    aliasDerivados: [
      "agurto tello",
      "agurto teyo",
      "al tello",
      "al teyo",
      "del tello",
      "del teyo",
      "el tello",
      "el teyo",
      "hospital agurto tello",
      "hospital agurto teyo",
      "hospital de agurto tello",
      "hospital de agurto teyo",
      "hospital de jose agurto tello",
      "hospital de jose agurto teyo",
      "hospital de tello",
      "hospital de teyo",
      "hospital jose agurto teyo",
      "hospital tello",
      "hospital teyo",
      "jose agurto tello",
      "jose agurto teyo",
      "la tello",
      "la teyo",
    ],
    titular: {
      cargo: "Director Ejecutivo",
      cargosEquivalentes: ["Director General", "Director del Hospital"],
      nombre: "Juan Pablo Sachun Alanya",
    },
    destinoSiTitular: { texto: "DIRIS LIMA ESTE (Dirección de Redes Integradas de Salud Lima Este)", entidadDestinoCodigo: "diris-le" },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "honadomani-sb",
    nombre: "Hospital Nacional Docente Madre Niño San Bartolomé",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HONADOMANI SB", "HONADOMANI", "Hospital San Bartolomé", "el Honadomani"],
    aliasDerivados: [
      "hospital de madre nino san bartolome",
      "hospital madre nino san bartolome",
      "hospital nacional madre nino san bartolome",
    ],
    titular: {
      cargo: "Director General",
      cargosEquivalentes: ["Director Ejecutivo", "Director del Hospital"],
      nombre: "Aldo César Benel Chamaya",
    },
    destinoSiTitular: { texto: "DIRIS LIMA CENTRO (Dirección de Redes Integradas de Salud Lima Centro)", entidadDestinoCodigo: "diris-lc" },
    contactos: { OCI: null, SECRETARIA_TECNICA_PAD: null, INTEGRIDAD: null, PROCURADOR: null },
    huecos: [
      HuecoCatalogo.SIN_OCI,
      HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD,
      HuecoCatalogo.SIN_INTEGRIDAD,
      HuecoCatalogo.SIN_PROCURADOR,
      HuecoCatalogo.SIN_CONTACTOS,
    ],
  },
  {
    codigo: "hlev",
    nombre: "Hospital de Lima Este Vitarte",
    tipo: TipoEntidad.HOSPITAL,
    alias: ["HLEV", "Hospital Vitarte", "Hospital de Lima Este"],
    aliasDerivados: [
      "hospital bitarte",
      "hospital de bitarte",
      "hospital de lima este bitarte",
      "hospital de vitarte",
      "hospital lima este bitarte",
      "hospital lima este vitarte",
    ],
    titular: {
      cargo: "Director",
      cargosEquivalentes: ["Director General", "Director Ejecutivo", "Director del Hospital"],
      nombre: "Hugo Wiliam Peña Lovaton",
    },
    destinoSiTitular: { texto: "DIRIS LIMA ESTE (Dirección de Redes Integradas de Salud Lima Este)", entidadDestinoCodigo: "diris-le" },
    contactos: {
      OCI: [{ nombre: "Graciela Quito Rivera", cargo: "Jefa del OCI", correo: "gquito@hlev.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Ramón Farro Samamé",
          cargo: "Secretario Técnico del Procedimiento Administrativo Disciplinario",
          correo: "rfarro@hlev.gob.pe",
        },
      ],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "cenares",
    nombre: "Centro Nacional de Abastecimiento de Recursos Estratégicos en Salud",
    tipo: TipoEntidad.CENTRO,
    alias: ["CENARES"],
    aliasDerivados: [],
    titular: {
      cargo: "Directora General",
      cargosEquivalentes: ["Director General", "Director Ejecutivo"],
      nombre: "Patricia Isabel Suárez Beyodas",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Livia Militza Calizaya De La Sota", cargo: "Jefa del OCI", correo: "lcalizaya@contraloria.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "José Antonio Vargas Molina",
          cargo: "Secretario Técnico Suplente de los Órganos Instructores",
          correo: "jvargas@cenares.gob.pe",
        },
      ],
      INTEGRIDAD: [
        { nombre: "Romelia Clorinda Paredes Tuesta", cargo: "Oficial (e) de Integridad Institucional", correo: "rparedes@cenares.gob.pe" },
      ],
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "pronis",
    nombre: "Programa Nacional de Inversiones en Salud",
    tipo: TipoEntidad.PROGRAMA,
    alias: ["PRONIS"],
    aliasDerivados: [],
    titular: { cargo: "Coordinador General", cargosEquivalentes: ["Director Ejecutivo"], nombre: "David Guillermo Miranda Herrera" },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Jesús Enrique Echavarria Pomalaza", cargo: "Jefe del OCI", correo: null }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "diris-le",
    nombre: "Dirección General de Redes Integradas de Salud Lima Este",
    tipo: TipoEntidad.DIRIS,
    alias: ["DIRIS Lima Este", "DIRIS de Lima Este", "Dirección de Redes Integradas de Salud Lima Este"],
    aliasDerivados: [],
    titular: { cargo: "DIRECTOR GENERAL", cargosEquivalentes: ["Director de la DIRIS"], nombre: "Norberto Yamunaqué Asanza" },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Katia Fabiola Ortiz Yañez", cargo: "Jefa del OCI", correo: "kortiz@dirislimaeste.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "diris-ln",
    nombre: "Dirección General de Redes Integradas de Salud Lima Norte",
    tipo: TipoEntidad.DIRIS,
    alias: ["DIRIS LN", "DIRIS Lima Norte", "DIRIS de Lima Norte", "Dirección de Redes Integradas de Salud Lima Norte"],
    aliasDerivados: [],
    titular: {
      cargo: "DIRECTORA GENERAL",
      cargosEquivalentes: ["Director General", "Director de la DIRIS"],
      nombre: "Libny Betsabeth More Huamán",
    },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Elizabeth Ruth Ríos Chuquinaupa", cargo: "Jefa del OCI", correo: "elizabeth.rios@dirisln.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Luis Alberto David Orcotoma Machuca",
          cargo: "Secretario Técnico del Procedimiento Administrativo Disciplinario",
          correo: "luis.orcotoma@dirisln.gob.pe",
        },
      ],
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "diris-lc",
    nombre: "Dirección General de Redes Integradas de Salud Lima Centro",
    tipo: TipoEntidad.DIRIS,
    alias: ["DIRIS LC", "DIRIS Lima Centro", "DIRIS de Lima Centro", "Dirección de Redes Integradas de Salud Lima Centro"],
    aliasDerivados: [],
    titular: { cargo: "Director General", cargosEquivalentes: ["Director de la DIRIS"], nombre: "Julio Miguel Flores Retuerto" },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Lisbeth Carolina Lopez Peña", cargo: "Jefa del OCI", correo: "oci@dirislimacentro.gob.pe" }],
      SECRETARIA_TECNICA_PAD: null,
      INTEGRIDAD: null,
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_SECRETARIA_TECNICA_PAD, HuecoCatalogo.SIN_INTEGRIDAD, HuecoCatalogo.SIN_PROCURADOR],
  },
  {
    codigo: "diris-ls",
    nombre: "Dirección General de Redes Integradas de Salud Lima Sur",
    tipo: TipoEntidad.DIRIS,
    alias: ["DIRIS LS", "DIRIS Lima Sur", "DIRIS de Lima Sur", "Dirección de Redes Integradas de Salud Lima Sur"],
    aliasDerivados: [],
    titular: { cargo: "Director General", cargosEquivalentes: ["Director de la DIRIS"], nombre: "Mario Eduardo Izquierdo Hernández" },
    destinoSiTitular: {
      texto: "ST PAD MINSA (Secretaría Técnica del Procedimiento Administrativo Disciplinario del MINSA)",
      entidadDestinoCodigo: "st-pad-minsa",
    },
    contactos: {
      OCI: [{ nombre: "Merici De Los Ángeles Huertas Navarro", cargo: "Jefa del OCI", correo: "mhuertas@dirislimasur.gob.pe" }],
      SECRETARIA_TECNICA_PAD: [
        {
          nombre: "Carlos Felix Vega Venegas",
          cargo: "Secretario Técnico de los Órganos Instructores",
          correo: "cvega@dirislimasur.gob.pe",
        },
      ],
      INTEGRIDAD: [
        {
          nombre: "Jair Alexander Patiño la Rosa",
          cargo: "Jefe de la Oficina de Integridad Institucional",
          correo: "jpatino@dirislimasur.gob.pe",
        },
      ],
      PROCURADOR: null,
    },
    huecos: [HuecoCatalogo.SIN_PROCURADOR],
  },
];
